import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "./lib/supabase";

type Condominium={id:number;name:string};
type RegisterItem={id:string;condominium_id:string;item_type:string;category:string;title:string;location:string;responsible:string;expiry_date:string|null;status:string;notes:string};
type Supplier={id:string;condominium_id:string;business_name:string;contact_name:string;fiscal_code:string;vat_number:string;email:string;phone:string;category:string;contract_start:string|null;contract_end:string|null;notes:string};

export default function RegisterPage({workspaceId,condominiums,isAdministrator=false}:{workspaceId:string;condominiums:Condominium[];isAdministrator?:boolean}){
 const [selected,setSelected]=useState<number|"all">(condominiums[0]?.id??"all");
 const [dbId,setDbId]=useState<string|null>(null); const [items,setItems]=useState<RegisterItem[]>([]); const [suppliers,setSuppliers]=useState<Supplier[]>([]);
 const [tab,setTab]=useState<"registro"|"fornitori">("registro"); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({item_type:"Sicurezza",category:"Impianti",title:"",location:"",responsible:"",expiry_date:"",status:"Attivo",notes:""});
 const [supplierForm,setSupplierForm]=useState({business_name:"",contact_name:"",fiscal_code:"",vat_number:"",email:"",phone:"",category:"",contract_start:"",contract_end:"",notes:""});
 const [editing,setEditing]=useState<string|null>(null); const [editingSupplier,setEditingSupplier]=useState<string|null>(null);

 async function resolve(){if(!supabase||selected==="all"){setDbId(null);return;}const {data,error}=await supabase.from("condominiums").select("id").eq("workspace_id",workspaceId).eq("legacy_id",selected).maybeSingle();if(error)throw error;setDbId(data?.id??null);}
 async function load(){if(!supabase){setLoading(false);return;}setLoading(true);setError("");try{await resolve();let q= supabase.from("condominium_register_items").select("*").eq("workspace_id",workspaceId).order("expiry_date");let s=supabase.from("condominium_suppliers").select("*").eq("workspace_id",workspaceId).order("business_name");const [a,b]=await Promise.all([q,s]);if(a.error)throw a.error;if(b.error)throw b.error;setItems(a.data??[]);setSuppliers(b.data??[]);}catch(e:any){setError(e?.message||"Impossibile caricare il registro.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[workspaceId,selected]);

 const scopedItems=useMemo(()=>dbId?items.filter(x=>x.condominium_id===dbId):[],[items,dbId]); const scopedSuppliers=useMemo(()=>dbId?suppliers.filter(x=>x.condominium_id===dbId):[],[suppliers,dbId]);
 const today=new Date().toISOString().slice(0,10);
 const expiring=scopedItems.filter(x=>x.expiry_date&&x.expiry_date<=new Date(Date.now()+30*86400000).toISOString().slice(0,10));
 async function saveItem(e:React.FormEvent){e.preventDefault();if(!supabase||!dbId||!form.title.trim())return;setSaving(true);setError("");try{const payload={workspace_id:workspaceId,condominium_id:dbId,...form,expiry_date:form.expiry_date||null,title:form.title.trim()};const q=editing?supabase.from("condominium_register_items").update(payload).eq("id",editing).eq("workspace_id",workspaceId):supabase.from("condominium_register_items").insert(payload);const {error}=await q;if(error)throw error;setEditing(null);setForm({item_type:"Sicurezza",category:"Impianti",title:"",location:"",responsible:"",expiry_date:"",status:"Attivo",notes:""});await load();}catch(e:any){setError(e?.message||"Impossibile salvare la voce.");}finally{setSaving(false);}}
 async function saveSupplier(e:React.FormEvent){e.preventDefault();if(!supabase||!dbId||!supplierForm.business_name.trim())return;setSaving(true);setError("");try{const payload={workspace_id:workspaceId,condominium_id:dbId,...supplierForm,contract_start:supplierForm.contract_start||null,contract_end:supplierForm.contract_end||null,business_name:supplierForm.business_name.trim()};const q=editingSupplier?supabase.from("condominium_suppliers").update(payload).eq("id",editingSupplier).eq("workspace_id",workspaceId):supabase.from("condominium_suppliers").insert(payload);const {error}=await q;if(error)throw error;setEditingSupplier(null);setSupplierForm({business_name:"",contact_name:"",fiscal_code:"",vat_number:"",email:"",phone:"",category:"",contract_start:"",contract_end:"",notes:""});await load();}catch(e:any){setError(e?.message||"Impossibile salvare il fornitore.");}finally{setSaving(false);}}
 async function remove(table:string,id:string,label:string){if(!supabase||!window.confirm("Sei sicuro di voler cancellare "+label+"?"))return;const {error}=await supabase.from(table).delete().eq("id",id).eq("workspace_id",workspaceId);if(error){setError(error.message);return;}await load();}
 return <section className="page-section">
  <div className="page-header"><div><span className="eyebrow">Anagrafe tecnica e operativa</span><h1>Registro condominiale</h1><p>Sicurezza, impianti, scadenze tecniche, documenti operativi e fornitori collegati al condominio.</p></div></div>
  <div className="filter-bar"><label>Condominio<select value={String(selected)} onChange={e=>setSelected(e.target.value==="all"?"all":Number(e.target.value))}><option value="all">Seleziona condominio</option>{condominiums.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
  {error&&<div className="error-box">{error}</div>}
  {dbId&&<><div className="tabs"><button className={tab==="registro"?"active":""} onClick={()=>setTab("registro")}>Sicurezza e impianti</button><button className={tab==="fornitori"?"active":""} onClick={()=>setTab("fornitori")}>Fornitori</button></div>
  {tab==="registro"&&<section className="cards-grid"><article className="card"><div className="section-heading"><div><h2>Registro tecnico</h2><p>{scopedItems.length} elementi · {expiring.length} con scadenza entro 30 giorni.</p></div>{isAdministrator&&<button className="primary-button" onClick={()=>{setEditing(null);setForm({item_type:"Sicurezza",category:"Impianti",title:"",location:"",responsible:"",expiry_date:"",status:"Attivo",notes:""})}}>+ Nuova voce</button>}</div>{loading?<p>Caricamento…</p>:scopedItems.length===0?<p>Nessuna voce registrata.</p>:scopedItems.map(x=><article className="row-card" key={x.id}><div><b>{x.title}</b><small>{x.item_type} · {x.category} · {x.location||"ubicazione non indicata"}</small><span>{x.status} · {x.expiry_date?"Scadenza "+x.expiry_date:"nessuna scadenza"}{x.responsible?" · "+x.responsible:""}</span>{x.notes&&<small>{x.notes}</small>}</div>{isAdministrator&&<div className="row-actions"><button className="secondary-button small" onClick={()=>{setEditing(x.id);setForm({item_type:x.item_type,category:x.category,title:x.title,location:x.location,responsible:x.responsible,expiry_date:x.expiry_date||"",status:x.status,notes:x.notes})}}>Modifica</button><button className="mini-danger" onClick={()=>remove("condominium_register_items",x.id,"la voce del registro")}>×</button></div>}</article>)}</article>
  <article className="card"><h2>Categorie consigliate</h2><p>Ascensore · antincendio · elettrico · gas · acqua · riscaldamento · cancello · autoclave · sicurezza · assicurazione.</p><div className="permission-box"><b>Scadenze</b><span>Le scadenze tecniche possono essere collegate alla gestione operativa e alle attività di BETHAG.</span></div></article></section>}
  {tab==="fornitori"&&<section className="cards-grid"><article className="card"><div className="section-heading"><div><h2>Fornitori</h2><p>Anagrafica dei soggetti che operano per il condominio.</p></div>{isAdministrator&&<button className="primary-button" onClick={()=>{setEditingSupplier(null);setSupplierForm({business_name:"",contact_name:"",fiscal_code:"",vat_number:"",email:"",phone:"",category:"",contract_start:"",contract_end:"",notes:""})}}>+ Nuovo fornitore</button>}</div>{scopedSuppliers.map(x=><article className="row-card" key={x.id}><div><b>{x.business_name}</b><small>{x.category||"Categoria non indicata"} · {x.contact_name||"Referente non indicato"}</small><span>{x.email||""}{x.phone?" · "+x.phone:""}{x.contract_end?" · contratto fino al "+x.contract_end:""}</span></div>{isAdministrator&&<div className="row-actions"><button className="secondary-button small" onClick={()=>{setEditingSupplier(x.id);setSupplierForm({business_name:x.business_name,contact_name:x.contact_name,fiscal_code:x.fiscal_code,vat_number:x.vat_number,email:x.email,phone:x.phone,category:x.category,contract_start:x.contract_start||"",contract_end:x.contract_end||"",notes:x.notes})}}>Modifica</button><button className="mini-danger" onClick={()=>remove("condominium_suppliers",x.id,"il fornitore")}>×</button></div>}</article>)}</article></section>}
  </>}
  {isAdministrator&&editing!==null&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveItem}><h2>Modifica voce registro</h2><div className="form-grid"><label>Tipo<select value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value})}><option>Sicurezza</option><option>Impianto</option><option>Assicurazione</option><option>Adempimento</option></select></label><label>Categoria<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label></div><label>Titolo<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label>Ubicazione<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Responsabile<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></label></div><div className="form-grid"><label>Scadenza<input type="date" value={form.expiry_date} onChange={e=>setForm({...form,expiry_date:e.target.value})}/></label><label>Stato<input value={form.status} onChange={e=>setForm({...form,status:e.target.value})}/></label></div><label>Note<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Annulla</button><button className="primary-button" disabled={saving}>Salva</button></div></form></div>}
  {isAdministrator&&editingSupplier!==null&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveSupplier}><h2>Modifica fornitore</h2><div className="form-grid"><label>Ragione sociale<input required value={supplierForm.business_name} onChange={e=>setSupplierForm({...supplierForm,business_name:e.target.value})}/></label><label>Categoria<input value={supplierForm.category} onChange={e=>setSupplierForm({...supplierForm,category:e.target.value})}/></label></div><label>Referente<input value={supplierForm.contact_name} onChange={e=>setSupplierForm({...supplierForm,contact_name:e.target.value})}/></label><div className="form-grid"><label>Codice fiscale<input value={supplierForm.fiscal_code} onChange={e=>setSupplierForm({...supplierForm,fiscal_code:e.target.value})}/></label><label>Partita IVA<input value={supplierForm.vat_number} onChange={e=>setSupplierForm({...supplierForm,vat_number:e.target.value})}/></label></div><div className="form-grid"><label>Email<input type="email" value={supplierForm.email} onChange={e=>setSupplierForm({...supplierForm,email:e.target.value})}/></label><label>Telefono<input value={supplierForm.phone} onChange={e=>setSupplierForm({...supplierForm,phone:e.target.value})}/></label></div><div className="form-grid"><label>Inizio contratto<input type="date" value={supplierForm.contract_start} onChange={e=>setSupplierForm({...supplierForm,contract_start:e.target.value})}/></label><label>Fine contratto<input type="date" value={supplierForm.contract_end} onChange={e=>setSupplierForm({...supplierForm,contract_end:e.target.value})}/></label></div><label>Note<textarea value={supplierForm.notes} onChange={e=>setSupplierForm({...supplierForm,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setEditingSupplier(null)}>Annulla</button><button className="primary-button" disabled={saving}>Salva</button></div></form></div>}
 </section>
}
