-- Reconcile public indexes with production.

drop index if exists public.portal_registration_requests_email_idx;
drop index if exists public.portal_registration_requests_status_idx;
drop index if exists public.portal_registration_requests_workspace_idx;
CREATE INDEX IF NOT EXISTS activities_condominium_id_idx ON public.activities USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS assemblies_condominium_id_idx ON public.assemblies USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS communications_condominium_id_idx ON public.communications USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_budgets_condominium_fk_idx ON public.condominium_budgets USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_budgets_fiscal_year_fk_idx ON public.condominium_budgets USING btree (fiscal_year_id);
CREATE INDEX IF NOT EXISTS condominium_budgets_workspace_year_idx ON public.condominium_budgets USING btree (workspace_id, condominium_id, fiscal_year_id);
CREATE INDEX IF NOT EXISTS condominium_creation_intakes_created_condominium_idx ON public.condominium_creation_intakes USING btree (created_condominium_id) WHERE (created_condominium_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS condominium_creation_intakes_workspace_status_idx ON public.condominium_creation_intakes USING btree (workspace_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS condominium_expense_allocations_condominium_idx ON public.condominium_expense_allocations USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_expense_allocations_ledger_idx ON public.condominium_expense_allocations USING btree (ledger_entry_id);
CREATE INDEX IF NOT EXISTS condominium_expense_allocations_member_idx ON public.condominium_expense_allocations USING btree (member_id);
CREATE INDEX IF NOT EXISTS condominium_expense_allocations_table_idx ON public.condominium_expense_allocations USING btree (allocation_table_id);
CREATE INDEX IF NOT EXISTS condominium_expense_allocations_unit_idx ON public.condominium_expense_allocations USING btree (unit_id);
CREATE INDEX IF NOT EXISTS condominium_expense_allocations_workspace_idx ON public.condominium_expense_allocations USING btree (workspace_id);
CREATE UNIQUE INDEX IF NOT EXISTS condominium_fiscal_carryovers_unique_period_position ON public.condominium_fiscal_carryovers USING btree (workspace_id, condominium_id, source_fiscal_year_id, target_fiscal_year_id, unit_id, COALESCE(member_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX IF NOT EXISTS condominium_fiscal_years_condominium_idx ON public.condominium_fiscal_years USING btree (condominium_id);
CREATE UNIQUE INDEX IF NOT EXISTS condominium_fiscal_years_unique ON public.condominium_fiscal_years USING btree (condominium_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS condominium_fiscal_years_workspace_idx ON public.condominium_fiscal_years USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS condominium_funds_condominium_idx ON public.condominium_funds USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_funds_workspace_idx ON public.condominium_funds USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS condominium_installments_condominium_idx ON public.condominium_installments USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_installments_due_date_idx ON public.condominium_installments USING btree (due_date);
CREATE INDEX IF NOT EXISTS condominium_installments_fiscal_year_fk_idx ON public.condominium_installments USING btree (fiscal_year_id);
CREATE INDEX IF NOT EXISTS condominium_installments_member_idx ON public.condominium_installments USING btree (member_id);
CREATE INDEX IF NOT EXISTS condominium_installments_unit_idx ON public.condominium_installments USING btree (unit_id);
CREATE INDEX IF NOT EXISTS condominium_installments_workspace_idx ON public.condominium_installments USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS idx_condominium_installments_ledger_entry_id ON public.condominium_installments USING btree (ledger_entry_id);
CREATE INDEX IF NOT EXISTS condominium_insurance_policies_condominium_id_idx ON public.condominium_insurance_policies USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS idx_condominium_insurance_policies_condo ON public.condominium_insurance_policies USING btree (workspace_id, condominium_id, end_date);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_assembly_id_idx ON public.condominium_ledger_entries USING btree (assembly_id);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_condominium_idx ON public.condominium_ledger_entries USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_deliberation_date_idx ON public.condominium_ledger_entries USING btree (condominium_id, deliberation_date) WHERE (deliberation_date IS NOT NULL);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_document_idx ON public.condominium_ledger_entries USING btree (document_id);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_fiscal_year_idx ON public.condominium_ledger_entries USING btree (fiscal_year_id);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_lookup ON public.condominium_ledger_entries USING btree (condominium_id, entry_date);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_member_idx ON public.condominium_ledger_entries USING btree (member_id);
CREATE UNIQUE INDEX IF NOT EXISTS condominium_ledger_entries_outgoing_document_key ON public.condominium_ledger_entries USING btree (document_id) WHERE ((direction = 'Uscita'::text) AND (document_id IS NOT NULL));
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_supplier_idx ON public.condominium_ledger_entries USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_unit_idx ON public.condominium_ledger_entries USING btree (unit_id);
CREATE INDEX IF NOT EXISTS condominium_ledger_entries_workspace_idx ON public.condominium_ledger_entries USING btree (workspace_id);
CREATE UNIQUE INDEX IF NOT EXISTS condominium_millesimal_tables_active_one_uidx ON public.condominium_millesimal_tables USING btree (condominium_id) WHERE active;
CREATE INDEX IF NOT EXISTS condominium_millesimal_tables_condominium_idx ON public.condominium_millesimal_tables USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_millesimal_tables_scope_mode_idx ON public.condominium_millesimal_tables USING btree (workspace_id, condominium_id, scope_mode);
CREATE UNIQUE INDEX IF NOT EXISTS condominium_millesimal_tables_workspace_condominium_name_uidx ON public.condominium_millesimal_tables USING btree (workspace_id, condominium_id, lower(btrim(name)));
CREATE INDEX IF NOT EXISTS condominium_millesimal_tables_workspace_idx ON public.condominium_millesimal_tables USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS condominium_millesimal_values_condominium_fk_idx ON public.condominium_millesimal_values USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_millesimal_values_table_idx ON public.condominium_millesimal_values USING btree (table_id);
CREATE INDEX IF NOT EXISTS condominium_millesimal_values_unit_idx ON public.condominium_millesimal_values USING btree (unit_id);
CREATE INDEX IF NOT EXISTS condominium_millesimal_values_workspace_idx ON public.condominium_millesimal_values USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS condominium_payment_movements_condominium_fk_idx ON public.condominium_payment_movements USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_payment_movements_installment_idx ON public.condominium_payment_movements USING btree (installment_id);
CREATE INDEX IF NOT EXISTS condominium_payment_movements_workspace_idx ON public.condominium_payment_movements USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS condominium_requests_condominium_id_idx ON public.condominium_requests USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS condominium_requests_condominium_status_idx ON public.condominium_requests USING btree (condominium_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS condominium_requests_member_id_idx ON public.condominium_requests USING btree (member_id);
CREATE INDEX IF NOT EXISTS condominium_requests_requester_idx ON public.condominium_requests USING btree (requester_user_id, created_at DESC) WHERE (requester_user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS condominium_requests_requester_user_id_idx ON public.condominium_requests USING btree (requester_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS condominium_work_documents_work_document_key ON public.condominium_work_documents USING btree (work_id, document_id);
CREATE INDEX IF NOT EXISTS deadlines_condominium_id_idx ON public.deadlines USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS documents_ai_status_idx ON public.documents USING btree (workspace_id, condominium_id, COALESCE((data ->> 'aiStatus'::text), 'Non elaborato'::text), updated_at DESC);
CREATE INDEX IF NOT EXISTS documents_condominium_id_idx ON public.documents USING btree (condominium_id);
CREATE INDEX IF NOT EXISTS documents_size_idx ON public.documents USING btree (file_size_bytes) WHERE (file_size_bytes IS NOT NULL);
CREATE INDEX IF NOT EXISTS suppliers_condominium_id_idx ON public.suppliers USING btree (condominium_id);
