-- BETHAG: transactional confirmation for cadastral unit transformations.
-- Deployment intentionally pending database-side validation.
-- The function must:
-- 1) authenticate the caller and verify condominium-management permission;
-- 2) lock the transformation and require Bozza status;
-- 3) validate Fusione/Frazionamento source/destination cardinality;
-- 4) block unresolved accounting balances;
-- 5) require millesimal/accounting review resolution;
-- 6) snapshot accounting and millesimal state;
-- 7) create destination units and genealogy items;
-- 8) explicitly assign selected members;
-- 9) mark source units Storica without physical deletion;
-- 10) finalize the transformation atomically.
--
-- NOTE: This migration is a design placeholder only until the database safety
-- validation permits installation of the transactional function.
