begin;
alter table public.condominium_units alter column unit_code set not null;
alter table public.condominium_members drop constraint if exists condominium_members_unit_id_fkey;
alter table public.condominium_members add constraint condominium_members_unit_id_fkey foreign key(unit_id) references public.condominium_units(id) on delete set null;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_workspace_id_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_workspace_id_fkey foreign key(workspace_id) references public.workspaces(id) on delete cascade;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_condominium_id_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_condominium_id_fkey foreign key(condominium_id) references public.condominiums(id) on delete cascade;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_unit_id_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_unit_id_fkey foreign key(unit_id) references public.condominium_units(id) on delete restrict;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_outgoing_member_id_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_outgoing_member_id_fkey foreign key(outgoing_member_id) references public.condominium_members(id) on delete restrict;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_incoming_member_id_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_incoming_member_id_fkey foreign key(incoming_member_id) references public.condominium_members(id) on delete restrict;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_created_by_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_created_by_fkey foreign key(created_by) references auth.users(id) on delete set null;
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_closed_by_fkey;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_closed_by_fkey foreign key(closed_by) references auth.users(id);
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_status_check;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_status_check check(status in ('Bozza','Confermato','Chiuso','Annullato'));
alter table public.condominium_member_transfers drop constraint if exists condominium_member_transfers_type_ck;
alter table public.condominium_member_transfers add constraint condominium_member_transfers_type_ck check(transfer_type in ('Vendita','Acquisto','Donazione','Successione','Altro'));
commit;