-- Provide a collision-safe legacy identifier for every newly created condominium member.
-- Existing legacy IDs are preserved. New RPC-created members use a reserved high range,
-- separate from the millisecond-based IDs generated by the legacy frontend.
begin;

create sequence if not exists public.condominium_members_legacy_id_seq as bigint;

lock table public.condominium_members in access exclusive mode;

select setval(
  'public.condominium_members_legacy_id_seq'::regclass,
  greatest(coalesce((select max(legacy_id) from public.condominium_members), 0), 8000000000000000) + 1,
  false
);

alter sequence public.condominium_members_legacy_id_seq
  owned by public.condominium_members.legacy_id;

alter table public.condominium_members
  alter column legacy_id
  set default nextval('public.condominium_members_legacy_id_seq'::regclass);

-- Inserts made by authenticated clients may use the column default.
-- The sequence only emits opaque numeric identifiers; table RLS remains authoritative.
grant usage, select on sequence public.condominium_members_legacy_id_seq to authenticated, service_role;

commit;
