-- Exact public function ACL parity with production.
do $$ declare r record; begin
  for r in select n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')' sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' loop
    execute format('revoke all on function %s from public, anon, authenticated, service_role', r.sig);
  end loop;
end $$;
grant execute on function public.admin_approve_portal_registration(p_request_id uuid, p_member_id uuid) to authenticated;
grant execute on function public.apply_resend_communication_event(p_provider_message_id text, p_event_id text, p_event_type text, p_email text, p_event_at timestamp with time zone) to service_role;
grant execute on function public.archive_condominium(p_workspace_id uuid, p_condominium_id uuid, p_reason text) to authenticated, service_role;
grant execute on function public.audit_condominium_work_change() to service_role;
grant execute on function public.audit_condominium_work_progress_change() to service_role;
grant execute on function public.audit_document_ai_change() to service_role;
grant execute on function public.claim_first_workspace_admin(p_workspace_id uuid) to authenticated, service_role;
grant execute on function public.clear_condominium_member_unit_legacy_fields() to service_role;
grant execute on function public.close_condominium_fiscal_year(p_workspace_id uuid, p_fiscal_year_id uuid) to authenticated, service_role;
grant execute on function public.close_condominium_member_transfer(p_transfer_id uuid) to authenticated, service_role;
grant execute on function public.close_fiscal_year_and_generate_carryovers(p_workspace_id uuid, p_condominium_id uuid, p_source_fiscal_year_id uuid) to authenticated, service_role;
grant execute on function public.compensate_fiscal_carryover(p_workspace_id uuid, p_condominium_id uuid, p_carryover_id uuid, p_amount numeric, p_target_installment_id uuid, p_notes text) to authenticated, service_role;
grant execute on function public.complete_portal_registration(p_full_name text, p_fiscal_code text, p_condominium_name text) to authenticated, service_role;
grant execute on function public.confirm_allocation_intake(p_workspace_id uuid, p_intake_id uuid) to authenticated, service_role;
grant execute on function public.confirm_condominium_creation_intake(p_intake_id uuid, p_condominium_id uuid) to authenticated, service_role;
grant execute on function public.confirm_condominium_member_transfer(p_unit_id uuid, p_outgoing_member_id uuid, p_incoming_name text, p_incoming_email text, p_incoming_user_id uuid, p_transfer_date date, p_transfer_type text, p_notes text, p_data jsonb) to authenticated, service_role;
grant execute on function public.delete_condominium(p_workspace_id uuid, p_legacy_id bigint, p_security_code text) to authenticated, service_role;
grant execute on function public.ensure_table_millesimal_values() to service_role;
grant execute on function public.ensure_unit_millesimal_values() to service_role;
grant execute on function public.generate_condominium_expense_allocations(p_workspace_id uuid, p_condominium_id uuid, p_ledger_entry_id uuid, p_table_id uuid, p_due_date date) to authenticated, service_role;
grant execute on function public.generate_consumption_allocations(p_workspace_id uuid, p_condominium_id uuid, p_ledger_entry_id uuid, p_fiscal_year_id uuid, p_service_type text) to authenticated, service_role;
grant execute on function public.generate_fiscal_year_carryovers(p_workspace_id uuid, p_condominium_id uuid, p_source_fiscal_year_id uuid, p_target_fiscal_year_id uuid) to authenticated, service_role;
grant execute on function public.generate_installments_from_allocations(p_workspace_id uuid, p_condominium_id uuid, p_ledger_entry_id uuid, p_title text, p_due_date date, p_fiscal_year_id uuid) to authenticated, service_role;
grant execute on function public.generate_installments_from_allocations_schedule(p_workspace_id uuid, p_condominium_id uuid, p_ledger_entry_id uuid, p_title text, p_due_dates date[], p_fiscal_year_id uuid, p_percentages numeric[], p_unify_by_member boolean) to authenticated, service_role;
grant execute on function public.get_member_transfer_accounting_snapshot(p_transfer_id uuid) to authenticated, service_role;
grant execute on function public.guard_condominium_expense_allocation_total() to service_role;
grant execute on function public.guard_confirmed_unit_transformation_immutable() to anon, authenticated, service_role;
grant execute on function public.guard_confirmed_unit_transformation_items_immutable() to anon, authenticated, service_role;
grant execute on function public.guard_consumption_reading_integrity() to service_role;
grant execute on function public.guard_expense_allocation_integrity() to service_role;
grant execute on function public.guard_fiscal_carryover_compensation_total() to service_role;
grant execute on function public.guard_fiscal_year_opening_balance() to service_role;
grant execute on function public.guard_fund_integrity() to service_role;
grant execute on function public.guard_installment_paid_amount_update() to authenticated, service_role;
grant execute on function public.guard_installment_parent_delete() to service_role;
grant execute on function public.guard_ledger_entry_integrity() to authenticated, service_role;
grant execute on function public.guard_ledger_parent_delete() to authenticated, service_role;
grant execute on function public.guard_millesimal_table_integrity() to authenticated, service_role;
grant execute on function public.guard_millesimal_table_parent_delete() to authenticated, service_role;
grant execute on function public.guard_millesimal_value_integrity() to authenticated, service_role;
grant execute on function public.guard_unit_scope_changes() to service_role;
grant execute on function public.list_archived_condominiums(p_workspace_id uuid) to authenticated, service_role;
grant execute on function public.normalize_condominium_member_contact() to service_role;
grant execute on function public.normalize_condominium_member_names() to service_role;
grant execute on function public.prepare_communication_recipients(p_communication_id uuid) to authenticated, service_role;
grant execute on function public.prevent_archived_condominium_mutation() to service_role;
grant execute on function public.prevent_closed_condominium_accounting() to service_role;
grant execute on function public.prevent_closed_fiscal_year_delete() to authenticated, service_role;
grant execute on function public.prevent_closed_fiscal_year_payment_delete() to authenticated, service_role;
grant execute on function public.prevent_closed_fiscal_year_record_mutation() to authenticated, service_role;
grant execute on function public.prevent_closed_fiscal_year_reopen() to service_role;
grant execute on function public.prevent_closed_fiscal_year_update() to authenticated, service_role;
grant execute on function public.prevent_condominium_unit_delete_with_financial_data() to authenticated, service_role;
grant execute on function public.prevent_condominium_unit_delete_with_members() to authenticated, service_role;
grant execute on function public.prevent_financial_unit_delete() to authenticated, service_role;
grant execute on function public.prevent_fiscal_year_delete() to service_role;
grant execute on function public.prevent_member_delete_with_financial_history() to authenticated, service_role;
grant execute on function public.prevent_member_unit_reassignment_with_financial_history() to authenticated, service_role;
grant execute on function public.prevent_paid_allocation_delete() to authenticated, service_role;
grant execute on function public.prevent_paid_installment_delete() to authenticated, service_role;
grant execute on function public.prevent_payment_core_mutation() to authenticated, service_role;
grant execute on function public.prevent_profile_privilege_self_change() to authenticated, service_role;
grant execute on function public.prevent_unsafe_condominium_unit_delete() to service_role;
grant execute on function public.preview_condominium_member_transfer(p_unit_id uuid, p_outgoing_member_id uuid, p_transfer_date date) to authenticated, service_role;
grant execute on function public.preview_condominium_unit_transformation(p_condominium_id uuid, p_transformation_type text, p_source_unit_ids uuid[]) to authenticated, service_role;
grant execute on function public.register_condominium_installment_payment(p_workspace_id uuid, p_condominium_id uuid, p_installment_id uuid, p_payment_date date, p_amount numeric, p_method text, p_reference text, p_notes text) to authenticated, service_role;
grant execute on function public.reset_stale_communication_recipients(p_communication_id uuid, p_age interval) to authenticated, service_role;
grant execute on function public.restore_condominium(p_workspace_id uuid, p_condominium_id uuid) to authenticated, service_role;
grant execute on function public.reverse_condominium_installment_payment(p_workspace_id uuid, p_condominium_id uuid, p_payment_id uuid, p_reason text) to authenticated, service_role;
grant execute on function public.save_condominium(p_workspace_id uuid, p_legacy_id bigint, p_name text, p_address text, p_city text, p_postal_code text, p_province text, p_data jsonb) to authenticated, service_role;
grant execute on function public.set_personal_security_code(p_code text, p_enabled boolean) to authenticated, service_role;
grant execute on function public.sync_condominium_expense_payment_status() to service_role;
grant execute on function public.sync_condominium_fund_usage() to service_role;
grant execute on function public.sync_condominium_installment_from_payments() to service_role;
grant execute on function public.sync_condominium_member_unit_legacy_fields() to service_role;
grant execute on function public.sync_condominium_work_financial_summary(p_work_id uuid) to service_role;
grant execute on function public.sync_condominium_work_financial_summary_trigger() to service_role;
grant execute on function public.touch_documents_updated_at() to anon, authenticated, service_role;
grant execute on function public.validate_allocation_rule_scope() to service_role;
grant execute on function public.validate_audit_scope() to service_role;
grant execute on function public.validate_communication_recipient_scope() to anon, authenticated, service_role;
grant execute on function public.validate_communication_scope() to service_role;
grant execute on function public.validate_condominium_allocation_intake_scope() to anon, authenticated, service_role;
grant execute on function public.validate_condominium_budget_scope() to service_role;
grant execute on function public.validate_condominium_consumption_reading_scope() to anon, authenticated, service_role;
grant execute on function public.validate_condominium_creation_intake_scope() to service_role;
grant execute on function public.validate_condominium_expense_allocation_scope() to service_role;
grant execute on function public.validate_condominium_expense_payment_status() to service_role;
grant execute on function public.validate_condominium_fiscal_year_scope() to service_role;
grant execute on function public.validate_condominium_fund_scope() to service_role;
grant execute on function public.validate_condominium_installment_paid_amount() to service_role;
grant execute on function public.validate_condominium_installment_scope() to service_role;
grant execute on function public.validate_condominium_installment_total() to service_role;
grant execute on function public.validate_condominium_ledger_fund_scope() to authenticated, service_role;
grant execute on function public.validate_condominium_ledger_scope() to service_role;
grant execute on function public.validate_condominium_legal_case_scope() to service_role;
grant execute on function public.validate_condominium_member_unit_scope() to service_role;
grant execute on function public.validate_condominium_millesimal_table_scope() to authenticated, service_role;
grant execute on function public.validate_condominium_millesimal_value_scope() to authenticated, service_role;
grant execute on function public.validate_condominium_payment_scope() to service_role;
grant execute on function public.validate_condominium_request_scope() to service_role;
grant execute on function public.validate_condominium_request_status() to anon, authenticated, service_role;
grant execute on function public.validate_condominium_tax_scope() to service_role;
grant execute on function public.validate_condominium_unit_relationship() to service_role;
grant execute on function public.validate_condominium_unit_workspace_scope() to authenticated, service_role;
grant execute on function public.validate_condominium_work_child_scope() to service_role;
grant execute on function public.validate_condominium_work_financial_scope() to authenticated, service_role;
grant execute on function public.validate_condominium_work_progress_accounting_links() to service_role;
grant execute on function public.validate_condominium_work_reference_scope() to authenticated, service_role;
grant execute on function public.validate_condominium_work_scope() to authenticated, service_role;
grant execute on function public.validate_document_ai_transition() to anon, authenticated, service_role;
grant execute on function public.validate_document_metadata() to anon, authenticated, service_role;
grant execute on function public.validate_document_upload_size(p_size_bytes bigint, p_warning_bytes bigint, p_max_bytes bigint) to authenticated, service_role;
grant execute on function public.validate_fiscal_carryover_compensation_scope() to service_role;
grant execute on function public.validate_fiscal_carryover_scope() to service_role;
grant execute on function public.validate_ledger_entry_deliberation_scope() to authenticated, service_role;
grant execute on function public.validate_portal_access_scope() to service_role;
grant execute on function public.validate_portal_registration_request_scope() to service_role;
grant execute on function public.validate_unit_owner_member_refs() to service_role;
grant execute on function public.validate_workspace_condominium_scope() to service_role;
grant execute on function public.verify_personal_security_code(p_code text) to authenticated, service_role;
