-- Exact public relation ACL parity with production.
do $$ declare r record; begin
  for r in select n.nspname||'.'||c.relname obj from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','v','m','f','p') loop
    execute format('revoke all on table %s from public, anon, authenticated, service_role', r.obj);
  end loop;
end $$;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.activities to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.assemblies to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.communication_recipients to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.communications to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_accounting_settings to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_allocation_intakes to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_allocation_rules to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_audit_log to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_budgets to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_consumption_readings to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_creation_intakes to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_expense_allocations to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_fiscal_carryover_compensations to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_fiscal_carryovers to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_fiscal_years to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_fund_availability to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_funds to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_installments to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_insurance_policies to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_ledger_entries to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_legal_cases to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_member_transfers to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_members to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_millesimal_tables to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_millesimal_values to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_payment_movements to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_payment_reversal_audit to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_register_items to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_requests to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_suppliers to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_tax_obligations to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_unit_transformation_items to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_unit_transformations to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_units to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_work_documents to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_work_events to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_work_progress to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominium_works to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.condominiums to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.deadlines to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.documents to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.portal_access to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.portal_registration_requests to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.profiles to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.suppliers to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.user_security_settings to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.workspace_members to authenticated,service_role;
grant delete,insert,maintain,references,select,trigger,truncate,update on table public.workspaces to authenticated,service_role;
